# Deep Fund Configuration
exp_name: "deepseek-test"

# Trading settings
cashflow: 100000
tickers:
  - MSFT
  - NVDA
  - TSLA

# Analysts to run, refer to graph.constants.py
workflow_analysts:
  - fundamental
  - news

# LLM model settings, refer to llm/inference.py: LLMConfig
llm:
  provider: "DeepSeek" 
  model: "deepseek-chat" # DeepSeek-V3