# Deep Fund Configuration
exp_name: "gold-etf-stock-deepseek"

# Trading settings
cashflow: 100000
tickers:
  - GLD
  - NEM
  - GOLD

# gold stock
# -NEM -GOLD -AEM
#gold etf 
# - GLD - IAU

# Analysts to run, refer to graph.constants.py
# —— fundamental and insider analyst not applicable to gold etf
workflow_analysts:
  # - fundamental
  # - insider
  # - news
  - technical
  - macroeconomic
  - policy
  

# LLM model settings, refer to llm/inference.py: LLMConfig
llm:
  provider: "DeepSeek" 
  model: "deepseek-chat" # DeepSeek-V3

